# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Youscrapy_mian.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
import os

fp = os.path.dirname(os.path.abspath(__file__))
fp = fp[:-4]

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(673, 563)
        MainWindow.setMinimumSize(QtCore.QSize(673, 563))
        MainWindow.setMaximumSize(QtCore.QSize(673, 563))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(fp + "/resource/Youscrapy_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 650, 90))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        # self.label_4 = QtWidgets.QLabel(self.groupBox)
        # self.label_4.setGeometry(QtCore.QRect(0, 3, 90, 80))
        # self.label_4.setText("")
        # self.label_4.setPixmap(QtGui.QPixmap(fp + "/resource/Youscrapy_icon.png"))
        # self.label_4.setScaledContents(True)
        # self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(20, 3, 640, 80))
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap(fp + "/resource/Youscrapy_title.png"))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 110, 650, 420))
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.textEdit_URL = QtWidgets.QLineEdit(self.groupBox_2)
        self.textEdit_URL.setGeometry(QtCore.QRect(10, 10, 560, 20))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.textEdit_URL.setFont(font)
        self.textEdit_URL.setObjectName("textEdit_URL")
        self.btn_Preview = QtWidgets.QPushButton(self.groupBox_2)
        self.btn_Preview.setGeometry(QtCore.QRect(570, 6, 70, 32))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.btn_Preview.setFont(font)
        self.btn_Preview.setObjectName("btn_Preview")
        self.label_thumbnail = QtWidgets.QLabel(self.groupBox_2)
        self.label_thumbnail.setGeometry(QtCore.QRect(314, 40, 320, 180))
        self.label_thumbnail.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.label_thumbnail.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_thumbnail.setLineWidth(1)
        self.label_thumbnail.setMidLineWidth(0)
        self.label_thumbnail.setText("")
        self.label_thumbnail.setPixmap(QtGui.QPixmap(fp + "/resource/YouTube.jpg"))
        self.label_thumbnail.setScaledContents(True)
        self.label_thumbnail.setObjectName("label_thumbnail")
        self.label_title = QtWidgets.QLabel(self.groupBox_2)
        self.label_title.setGeometry(QtCore.QRect(320, 230, 300, 50))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_title.setFont(font)
        self.label_title.setTextFormat(QtCore.Qt.AutoText)
        self.label_title.setScaledContents(False)
        self.label_title.setWordWrap(True)
        self.label_title.setOpenExternalLinks(False)
        self.label_title.setObjectName("label_title")
        self.combo_Stream = QtWidgets.QComboBox(self.groupBox_2)
        self.combo_Stream.setGeometry(QtCore.QRect(370, 300, 260, 26))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.combo_Stream.setFont(font)
        self.combo_Stream.setObjectName("combo_Stream")
        self.btn_Path = QtWidgets.QToolButton(self.groupBox_2)
        self.btn_Path.setGeometry(QtCore.QRect(580, 340, 50, 22))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.btn_Path.setFont(font)
        self.btn_Path.setObjectName("btn_Path")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.groupBox_2)
        self.plainTextEdit.setGeometry(QtCore.QRect(10, 40, 290, 320))
        self.plainTextEdit.setReadOnly(True)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.label_Path = QtWidgets.QLabel(self.groupBox_2)
        self.label_Path.setGeometry(QtCore.QRect(318, 344, 250, 16))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_Path.setFont(font)
        self.label_Path.setWordWrap(True)
        self.label_Path.setObjectName("label_Path")
        self.progressBar = QtWidgets.QProgressBar(self.groupBox_2)
        self.progressBar.setGeometry(QtCore.QRect(10, 380, 520, 30))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.btn_Download = QtWidgets.QPushButton(self.groupBox_2)
        self.btn_Download.setGeometry(QtCore.QRect(540, 380, 100, 32))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.btn_Download.setFont(font)
        self.btn_Download.setObjectName("btn_Download")
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setGeometry(QtCore.QRect(316, 305, 60, 16))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_Preview.setText(_translate("MainWindow", "확인"))
        self.label_title.setText(_translate("MainWindow", "Title 출력 라인 입니다.\n"
"멀티라인 테스트"))
        self.btn_Path.setText(_translate("MainWindow", "..."))
        self.label_Path.setText(_translate("MainWindow", "기본다운로드 경로"))
        self.btn_Download.setText(_translate("MainWindow", "다운로드"))
        self.label_5.setText(_translate("MainWindow", "화질"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
